"""
UI element representation schemas for GUI automation.
"""

from typing import Optional, Tuple, Literal
from pydantic import BaseModel, Field


class UIElement(BaseModel):
    """
    Represents a UI element found through any detection method.
    """

    element_type: str = Field(
        description="Type of element (button, textfield, window, etc.)"
    )
    label: Optional[str] = Field(
        default=None, description="Text label or name of the element"
    )
    role: Optional[str] = Field(
        default=None, description="Accessibility role of the element"
    )
    bounds: Tuple[int, int, int, int] = Field(
        description="Element bounds as (x, y, width, height)"
    )
    center: Tuple[int, int] = Field(
        description="Exact center coordinate for clicking (x, y)"
    )
    confidence: float = Field(
        description="Detection confidence score (0.0-1.0)", ge=0.0, le=1.0
    )
    detection_method: Literal["accessibility", "cv", "ocr", "vision"] = Field(
        description="Method used to detect this element"
    )


class SemanticTarget(BaseModel):
    """
    Semantic description of a UI element to locate.
    Generated by vision LLM to describe what to find.
    """

    description: str = Field(
        description="Human-readable description of the target (e.g., 'red Submit button')"
    )
    location_hint: Optional[str] = Field(
        default=None,
        description="Approximate location hint (e.g., 'bottom-right corner')",
    )
    text_content: Optional[str] = Field(
        default=None, description="Expected text on or near the element"
    )
    color_hint: Optional[str] = Field(
        default=None, description="Color description of the element"
    )
    expected_role: Optional[str] = Field(
        default=None,
        description="Expected accessibility role (button, textfield, etc.)",
    )
